---
title: "Initial EDA"
output: pdf_document
---
```{r}
#library(readxl)
install.packages("data.table")
install.packages("odbc")
install.packages("DBI")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("magrittr")
install.packages("tidymodels")
install.packages("tidyverse")
install.packages("moments")
install.packages("purrr")
install.packages("tidyr")
install.packages("naniar")
install.packages("stringr")
install.packages("xts")
```

```{r}
library(odbc)
library(DBI)
library(readxl)
library(dplyr)
library(magrittr)
library(data.table)
library(tidyverse)
library(moments)
library(ggplot2)
library(tidyr)
library(naniar)
library(stringr)
library(xts)
```



```{r}
con <- dbConnect(odbc(), Driver = "SQL Server", Server = "researchdb-t01",  Database = "Oesofaguschirurgie_TEST", UID = "dac_usr",PWD = "Welkom01", Port = 1433)

```

```{r}
overview <- as.data.frame(dbGetQuery(con, "SELECT Case_number,mode,Geslacht,Datum_operatie,Geboortedatum_nieuw,operatiejaar,Leeftijd_OK,Lengte,Gewicht,ASA,Pneumonie,Pneumonie_datum,Naadlekkage,Naadlke_datum,Ongecompliceerd,Reoperatie,Reinterventie_radiologisch,Reinterventie_scopisch,Pt_nummer,Overleden,Complicatie_divers,Ongecompliceerd_inf FROM OES_ST_V4_SHORT"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_SHORT'")$COLUMN_NAME), collapse = ",")
#columns_string
```


## GASTRO
```{r}
gastro <- as.data.frame(dbGetQuery(con, "SELECT Datum_operatie_nieuw,monster_dat_1,verslag_dat_1,monster_dat_2,verslag_dat_2,monster_dat_3,verslag_dat_3,monster_dat_4,verslag_dat_4,monster_dat_5,verslag_dat_5,verslag_5,verslag_1,verslag_2,verslag_3,verslag_4 FROM OES_ST_V4_GASTRO"))
```

## LAB
```{r}
## Too much typing of all column names, short work around
## 1 retrieve all column info from table, saved in df
#lab_columns <- dbGetQuery(con, "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_LAB'")
## 2 put COLUMN_NAME column into vector
#lab_list <- cbind(lab_columns$COLUMN_NAME)
## 3 Concatenate strings form the vector and separate by comma
#lab_colstr <- paste(lab_list, collapse = ",")
#lab_colstr
lab <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,LEUC_dag0_M1,LEUC_dag0_M2,LEUC_dag0_M3,LEUC_dag1_M1,LEUC_dag1_M2,LEUC_dag1_M3,LEUC_dag2_M1,LEUC_dag2_M2,LEUC_dag2_M3,LEUC_dag3_M1,LEUC_dag3_M2,LEUC_dag3_M3,LEUC_dag4_M1,LEUC_dag4_M2,LEUC_dag4_M3,LEUC_dag5_M1,LEUC_dag5_M2,LEUC_dag5_M3,LEUC_dag6_M1,LEUC_dag6_M2,LEUC_dag6_M3,LEUC_dag7_M1,LEUC_dag7_M2,LEUC_dag7_M3,LEUC_dag8_M1,LEUC_dag8_M2,LEUC_dag8_M3,LEUC_dag9_M1,LEUC_dag9_M2,LEUC_dag9_M3,LEUC_dag10_M1,LEUC_dag10_M2,LEUC_dag10_M3,LEUC_dag11_M1,LEUC_dag11_M2,LEUC_dag11_M3,LEUC_dag12_M1,LEUC_dag12_M2,LEUC_dag12_M3,LEUC_dag13_M1,LEUC_dag13_M2,LEUC_dag13_M3,LEUC_dag14_M1,LEUC_dag14_M2,LEUC_dag14_M3,AMY_dag0_M1,AMY_dag0_M2,AMY_dag0_M3,AMY_dag1_M1,AMY_dag1_M2,AMY_dag1_M3,AMY_dag2_M1,AMY_dag2_M2,AMY_dag2_M3,AMY_dag3_M1,AMY_dag3_M2,AMY_dag3_M3,AMY_dag4_M1,AMY_dag4_M2,AMY_dag4_M3,AMY_dag5_M1,AMY_dag5_M2,AMY_dag5_M3,AMY_dag6_M1,AMY_dag6_M2,AMY_dag6_M3,AMY_dag7_M1,AMY_dag7_M2,AMY_dag7_M3,AMY_dag8_M1,AMY_dag8_M2,AMY_dag8_M3,AMY_dag9_M1,AMY_dag9_M2,AMY_dag9_M3,AMY_dag10_M1,AMY_dag10_M2,AMY_dag10_M3,AMY_dag11_M1,AMY_dag11_M2,AMY_dag11_M3,AMY_dag12_M1,AMY_dag12_M2,AMY_dag12_M3,AMY_dag13_M1,AMY_dag13_M2,AMY_dag13_M3,AMY_dag14_M1,AMY_dag14_M2,AMY_dag14_M3,CRP_dag0_M1,CRP_dag0_M2,CRP_dag0_M3,CRP_dag1_M1,CRP_dag1_M2,CRP_dag1_M3,CRP_dag2_M1,CRP_dag2_M2,CRP_dag2_M3,CRP_dag3_M1,CRP_dag3_M2,CRP_dag3_M3,CRP_dag4_M1,CRP_dag4_M2,CRP_dag4_M3,CRP_dag5_M1,CRP_dag5_M2,CRP_dag5_M3,CRP_dag6_M1,CRP_dag6_M2,CRP_dag6_M3,CRP_dag7_M1,CRP_dag7_M2,CRP_dag7_M3,CRP_dag8_M1,CRP_dag8_M2,CRP_dag8_M3,CRP_dag9_M1,CRP_dag9_M2,CRP_dag9_M3,CRP_dag10_M1,CRP_dag10_M2,CRP_dag10_M3,CRP_dag11_M1,CRP_dag11_M2,CRP_dag11_M3,CRP_dag12_M1,CRP_dag12_M2,CRP_dag12_M3,CRP_dag13_M1,CRP_dag13_M2,CRP_dag13_M3,CRP_dag14_M1,CRP_dag14_M2,CRP_dag14_M3,HB_dag0_M1,HB_dag0_M2,HB_dag0_M3,HB_dag1_M1,HB_dag1_M2,HB_dag1_M3,HB_dag2_M1,HB_dag2_M2,HB_dag2_M3,HB_dag3_M1,HB_dag3_M2,HB_dag3_M3,HB_dag4_M1,HB_dag4_M2,HB_dag4_M3,HB_dag5_M1,HB_dag5_M2,HB_dag5_M3,HB_dag6_M1,HB_dag6_M2,HB_dag6_M3,HB_dag7_M1,HB_dag7_M2,HB_dag7_M3,HB_dag8_M1,HB_dag8_M2,HB_dag8_M3,HB_dag9_M1,HB_dag9_M2,HB_dag9_M3,HB_dag10_M1,HB_dag10_M2,HB_dag10_M3,HB_dag11_M1,HB_dag11_M2,HB_dag11_M3,HB_dag12_M1,HB_dag12_M2,HB_dag12_M3,HB_dag13_M1,HB_dag13_M2,HB_dag13_M3,HB_dag14_M1,HB_dag14_M2,HB_dag14_M3 FROM OES_ST_V4_LAB")) 
```

## OK VERSL
```{r}
## Too much typing of all column names, short work around
## 1 retrieve all column info from table, saved in df
#table_columns <- dbGetQuery(con, "SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_OK_VERSL'")
## 2 put COLUMN_NAME column into vector
#columns_vec <- cbind(table_columns$COLUMN_NAME)
## 3 Concatenate strings form the vector and separate by comma
#columns_string <- paste(columns_vec, collapse = ",")
#columns_string

okverslag <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,verrichting,ASA,code,operatienr,operatie_omsch_versl,verslag,hfdver FROM OES_ST_V4_OK_VERSL"))
```

RAD
```{r}
#columns_string <-paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_RAD'")$COLUMN_NAME), collapse = ",")
#columns_string

radiologie <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,accno_1,verr_1,datum_1,accno_2,verr_2,datum_2,accno_3,verr_3,datum_3,accno_4,verr_4,datum_4,accno_5,verr_5,datum_5,accno_6,verr_6,datum_6,accno_7,verr_7,datum_7,accno_8,verr_8,datum_8,accno_9,verr_9,datum_9,accno_10,verr_10,datum_10,accno_11,verr_11,datum_11,accno_12,verr_12,datum_12,accno_13,verr_13,datum_13,accno_14,verr_14,datum_14,accno_15,verr_15,datum_15,accno_16,verr_16,datum_16,accno_17,verr_17,datum_17,accno_18,verr_18,datum_18,accno_19,verr_19,datum_19,accno_20,verr_20,datum_20,verslag_1,verslag_2,verslag_3,verslag_4,verslag_5,verslag_6,verslag_7,verslag_8,verslag_9,verslag_10,verslag_11,verslag_12,verslag_13,verslag_14,verslag_15,verslag_16,verslag_17,verslag_18,verslag_19,verslag_20 FROM OES_ST_V4_RAD"))
```



## VITALS ABP
```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_ABP_auto_24'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_abp_auto <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,ABP1_dag1,ABP2_dag1,ABP3_dag1,ABP4_dag1,ABP5_dag1,ABP6_dag1,ABP7_dag1,ABP8_dag1,ABP9_dag1,ABP10_dag1,ABP11_dag1,ABP12_dag1,ABP13_dag1,ABP14_dag1,ABP15_dag1,ABP16_dag1,ABP17_dag1,ABP18_dag1,ABP19_dag1,ABP20_dag1,ABP21_dag1,ABP22_dag1,ABP23_dag1,ABP24_dag1,ABP1_dag2,ABP2_dag2,ABP3_dag2,ABP4_dag2,ABP5_dag2,ABP6_dag2,ABP7_dag2,ABP8_dag2,ABP9_dag2,ABP10_dag2,ABP11_dag2,ABP12_dag2,ABP13_dag2,ABP14_dag2,ABP15_dag2,ABP16_dag2,ABP17_dag2,ABP18_dag2,ABP19_dag2,ABP20_dag2,ABP21_dag2,ABP22_dag2,ABP23_dag2,ABP24_dag2,ABP1_dag3,ABP2_dag3,ABP3_dag3,ABP4_dag3,ABP5_dag3,ABP6_dag3,ABP7_dag3,ABP8_dag3,ABP9_dag3,ABP10_dag3,ABP11_dag3,ABP12_dag3,ABP13_dag3,ABP14_dag3,ABP15_dag3,ABP16_dag3,ABP17_dag3,ABP18_dag3,ABP19_dag3,ABP20_dag3,ABP21_dag3,ABP22_dag3,ABP23_dag3,ABP24_dag3,ABP1_dag4,ABP2_dag4,ABP3_dag4,ABP4_dag4,ABP5_dag4,ABP6_dag4,ABP7_dag4,ABP8_dag4,ABP9_dag4,ABP10_dag4,ABP11_dag4,ABP12_dag4,ABP13_dag4,ABP14_dag4,ABP15_dag4,ABP16_dag4,ABP17_dag4,ABP18_dag4,ABP19_dag4,ABP20_dag4,ABP21_dag4,ABP22_dag4,ABP23_dag4,ABP24_dag4,ABP1_dag5,ABP2_dag5,ABP3_dag5,ABP4_dag5,ABP5_dag5,ABP6_dag5,ABP7_dag5,ABP8_dag5,ABP9_dag5,ABP10_dag5,ABP11_dag5,ABP12_dag5,ABP13_dag5,ABP14_dag5,ABP15_dag5,ABP16_dag5,ABP17_dag5,ABP18_dag5,ABP19_dag5,ABP20_dag5,ABP21_dag5,ABP22_dag5,ABP23_dag5,ABP24_dag5,ABP1_dag6,ABP2_dag6,ABP3_dag6,ABP4_dag6,ABP5_dag6,ABP6_dag6,ABP7_dag6,ABP8_dag6,ABP9_dag6,ABP10_dag6,ABP11_dag6,ABP12_dag6,ABP13_dag6,ABP14_dag6,ABP15_dag6,ABP16_dag6,ABP17_dag6,ABP18_dag6,ABP19_dag6,ABP20_dag6,ABP21_dag6,ABP22_dag6,ABP23_dag6,ABP24_dag6,ABP1_dag7,ABP2_dag7,ABP3_dag7,ABP4_dag7,ABP5_dag7,ABP6_dag7,ABP7_dag7,ABP8_dag7,ABP9_dag7,ABP10_dag7,ABP11_dag7,ABP12_dag7,ABP13_dag7,ABP14_dag7,ABP15_dag7,ABP16_dag7,ABP17_dag7,ABP18_dag7,ABP19_dag7,ABP20_dag7,ABP21_dag7,ABP22_dag7,ABP23_dag7,ABP24_dag7,ABP1_dag8,ABP2_dag8,ABP3_dag8,ABP4_dag8,ABP5_dag8,ABP6_dag8,ABP7_dag8,ABP8_dag8,ABP9_dag8,ABP10_dag8,ABP11_dag8,ABP12_dag8,ABP13_dag8,ABP14_dag8,ABP15_dag8,ABP16_dag8,ABP17_dag8,ABP18_dag8,ABP19_dag8,ABP20_dag8,ABP21_dag8,ABP22_dag8,ABP23_dag8,ABP24_dag8,ABP1_dag9,ABP2_dag9,ABP3_dag9,ABP4_dag9,ABP5_dag9,ABP6_dag9,ABP7_dag9,ABP8_dag9,ABP9_dag9,ABP10_dag9,ABP11_dag9,ABP12_dag9,ABP13_dag9,ABP14_dag9,ABP15_dag9,ABP16_dag9,ABP17_dag9,ABP18_dag9,ABP19_dag9,ABP20_dag9,ABP21_dag9,ABP22_dag9,ABP23_dag9,ABP24_dag9,ABP1_dag10,ABP2_dag10,ABP3_dag10,ABP4_dag10,ABP5_dag10,ABP6_dag10,ABP7_dag10,ABP8_dag10,ABP9_dag10,ABP10_dag10,ABP11_dag10,ABP12_dag10,ABP13_dag10,ABP14_dag10,ABP15_dag10,ABP16_dag10,ABP17_dag10,ABP18_dag10,ABP19_dag10,ABP20_dag10,ABP21_dag10,ABP22_dag10,ABP23_dag10,ABP24_dag10,ABP1_dag11,ABP2_dag11,ABP3_dag11,ABP4_dag11,ABP5_dag11,ABP6_dag11,ABP7_dag11,ABP8_dag11,ABP9_dag11,ABP10_dag11,ABP11_dag11,ABP12_dag11,ABP13_dag11,ABP14_dag11,ABP15_dag11,ABP16_dag11,ABP17_dag11,ABP18_dag11,ABP19_dag11,ABP20_dag11,ABP21_dag11,ABP22_dag11,ABP23_dag11,ABP24_dag11,ABP1_dag12,ABP2_dag12,ABP3_dag12,ABP4_dag12,ABP5_dag12,ABP6_dag12,ABP7_dag12,ABP8_dag12,ABP9_dag12,ABP10_dag12,ABP11_dag12,ABP12_dag12,ABP13_dag12,ABP14_dag12,ABP15_dag12,ABP16_dag12,ABP17_dag12,ABP18_dag12,ABP19_dag12,ABP20_dag12,ABP21_dag12,ABP22_dag12,ABP23_dag12,ABP24_dag12,ABP1_dag13,ABP2_dag13,ABP3_dag13,ABP4_dag13,ABP5_dag13,ABP6_dag13,ABP7_dag13,ABP8_dag13,ABP9_dag13,ABP10_dag13,ABP11_dag13,ABP12_dag13,ABP13_dag13,ABP14_dag13,ABP15_dag13,ABP16_dag13,ABP17_dag13,ABP18_dag13,ABP19_dag13,ABP20_dag13,ABP21_dag13,ABP22_dag13,ABP23_dag13,ABP24_dag13,ABP1_dag14,ABP2_dag14,ABP3_dag14,ABP4_dag14,ABP5_dag14,ABP6_dag14,ABP7_dag14,ABP8_dag14,ABP9_dag14,ABP10_dag14,ABP11_dag14,ABP12_dag14,ABP13_dag14,ABP14_dag14,ABP15_dag14,ABP16_dag14,ABP17_dag14,ABP18_dag14,ABP19_dag14,ABP20_dag14,ABP21_dag14,ABP22_dag14,ABP23_dag14,ABP24_dag14 FROM OES_ST_V4_VITALS_ABP_auto_24"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_ABP_man_20'")$COLUMN_NAME), collapse = ",")
#columns_string
vitals_abp_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,ABP1_dag1,ABP2_dag1,ABP3_dag1,ABP4_dag1,ABP5_dag1,ABP6_dag1,ABP7_dag1,ABP8_dag1,ABP9_dag1,ABP10_dag1,ABP11_dag1,ABP12_dag1,ABP13_dag1,ABP14_dag1,ABP15_dag1,ABP16_dag1,ABP17_dag1,ABP18_dag1,ABP19_dag1,ABP20_dag1,ABP1_dag2,ABP2_dag2,ABP3_dag2,ABP4_dag2,ABP5_dag2,ABP6_dag2,ABP7_dag2,ABP8_dag2,ABP9_dag2,ABP10_dag2,ABP11_dag2,ABP12_dag2,ABP13_dag2,ABP14_dag2,ABP15_dag2,ABP16_dag2,ABP17_dag2,ABP18_dag2,ABP19_dag2,ABP20_dag2,ABP1_dag3,ABP2_dag3,ABP3_dag3,ABP4_dag3,ABP5_dag3,ABP6_dag3,ABP7_dag3,ABP8_dag3,ABP9_dag3,ABP10_dag3,ABP11_dag3,ABP12_dag3,ABP13_dag3,ABP14_dag3,ABP15_dag3,ABP16_dag3,ABP17_dag3,ABP18_dag3,ABP19_dag3,ABP20_dag3,ABP1_dag4,ABP2_dag4,ABP3_dag4,ABP4_dag4,ABP5_dag4,ABP6_dag4,ABP7_dag4,ABP8_dag4,ABP9_dag4,ABP10_dag4,ABP11_dag4,ABP12_dag4,ABP13_dag4,ABP14_dag4,ABP15_dag4,ABP16_dag4,ABP17_dag4,ABP18_dag4,ABP19_dag4,ABP20_dag4,ABP1_dag5,ABP2_dag5,ABP3_dag5,ABP4_dag5,ABP5_dag5,ABP6_dag5,ABP7_dag5,ABP8_dag5,ABP9_dag5,ABP10_dag5,ABP11_dag5,ABP12_dag5,ABP13_dag5,ABP14_dag5,ABP15_dag5,ABP16_dag5,ABP17_dag5,ABP18_dag5,ABP19_dag5,ABP20_dag5,ABP1_dag6,ABP2_dag6,ABP3_dag6,ABP4_dag6,ABP5_dag6,ABP6_dag6,ABP7_dag6,ABP8_dag6,ABP9_dag6,ABP10_dag6,ABP11_dag6,ABP12_dag6,ABP13_dag6,ABP14_dag6,ABP15_dag6,ABP16_dag6,ABP17_dag6,ABP18_dag6,ABP19_dag6,ABP20_dag6,ABP1_dag7,ABP2_dag7,ABP3_dag7,ABP4_dag7,ABP5_dag7,ABP6_dag7,ABP7_dag7,ABP8_dag7,ABP9_dag7,ABP10_dag7,ABP11_dag7,ABP12_dag7,ABP13_dag7,ABP14_dag7,ABP15_dag7,ABP16_dag7,ABP17_dag7,ABP18_dag7,ABP19_dag7,ABP20_dag7,ABP1_dag8,ABP2_dag8,ABP3_dag8,ABP4_dag8,ABP5_dag8,ABP6_dag8,ABP7_dag8,ABP8_dag8,ABP9_dag8,ABP10_dag8,ABP11_dag8,ABP12_dag8,ABP13_dag8,ABP14_dag8,ABP15_dag8,ABP16_dag8,ABP17_dag8,ABP18_dag8,ABP19_dag8,ABP20_dag8,ABP1_dag9,ABP2_dag9,ABP3_dag9,ABP4_dag9,ABP5_dag9,ABP6_dag9,ABP7_dag9,ABP8_dag9,ABP9_dag9,ABP10_dag9,ABP11_dag9,ABP12_dag9,ABP13_dag9,ABP14_dag9,ABP15_dag9,ABP16_dag9,ABP17_dag9,ABP18_dag9,ABP19_dag9,ABP20_dag9,ABP1_dag10,ABP2_dag10,ABP3_dag10,ABP4_dag10,ABP5_dag10,ABP6_dag10,ABP7_dag10,ABP8_dag10,ABP9_dag10,ABP10_dag10,ABP11_dag10,ABP12_dag10,ABP13_dag10,ABP14_dag10,ABP15_dag10,ABP16_dag10,ABP17_dag10,ABP18_dag10,ABP19_dag10,ABP20_dag10,ABP1_dag11,ABP2_dag11,ABP3_dag11,ABP4_dag11,ABP5_dag11,ABP6_dag11,ABP7_dag11,ABP8_dag11,ABP9_dag11,ABP10_dag11,ABP11_dag11,ABP12_dag11,ABP13_dag11,ABP14_dag11,ABP15_dag11,ABP16_dag11,ABP17_dag11,ABP18_dag11,ABP19_dag11,ABP20_dag11,ABP1_dag12,ABP2_dag12,ABP3_dag12,ABP4_dag12,ABP5_dag12,ABP6_dag12,ABP7_dag12,ABP8_dag12,ABP9_dag12,ABP10_dag12,ABP11_dag12,ABP12_dag12,ABP13_dag12,ABP14_dag12,ABP15_dag12,ABP16_dag12,ABP17_dag12,ABP18_dag12,ABP19_dag12,ABP20_dag12,ABP1_dag13,ABP2_dag13,ABP3_dag13,ABP4_dag13,ABP5_dag13,ABP6_dag13,ABP7_dag13,ABP8_dag13,ABP9_dag13,ABP10_dag13,ABP11_dag13,ABP12_dag13,ABP13_dag13,ABP14_dag13,ABP15_dag13,ABP16_dag13,ABP17_dag13,ABP18_dag13,ABP19_dag13,ABP20_dag13,ABP1_dag14,ABP2_dag14,ABP3_dag14,ABP4_dag14,ABP5_dag14,ABP6_dag14,ABP7_dag14,ABP8_dag14,ABP9_dag14,ABP10_dag14,ABP11_dag14,ABP12_dag14,ABP13_dag14,ABP14_dag14,ABP15_dag14,ABP16_dag14,ABP17_dag14,ABP18_dag14,ABP19_dag14,ABP20_dag14 FROM OES_ST_V4_VITALS_ABP_man_20"))
```

## VITALS AF
```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_AF_auto_24'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_af_auto <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,AF1_dag1,AF2_dag1,AF3_dag1,AF4_dag1,AF5_dag1,AF6_dag1,AF7_dag1,AF8_dag1,AF9_dag1,AF10_dag1,AF11_dag1,AF12_dag1,AF13_dag1,AF14_dag1,AF15_dag1,AF16_dag1,AF17_dag1,AF18_dag1,AF19_dag1,AF20_dag1,AF21_dag1,AF22_dag1,AF23_dag1,AF24_dag1,AF1_dag2,AF2_dag2,AF3_dag2,AF4_dag2,AF5_dag2,AF6_dag2,AF7_dag2,AF8_dag2,AF9_dag2,AF10_dag2,AF11_dag2,AF12_dag2,AF13_dag2,AF14_dag2,AF15_dag2,AF16_dag2,AF17_dag2,AF18_dag2,AF19_dag2,AF20_dag2,AF21_dag2,AF22_dag2,AF23_dag2,AF24_dag2,AF1_dag3,AF2_dag3,AF3_dag3,AF4_dag3,AF5_dag3,AF6_dag3,AF7_dag3,AF8_dag3,AF9_dag3,AF10_dag3,AF11_dag3,AF12_dag3,AF13_dag3,AF14_dag3,AF15_dag3,AF16_dag3,AF17_dag3,AF18_dag3,AF19_dag3,AF20_dag3,AF21_dag3,AF22_dag3,AF23_dag3,AF24_dag3,AF1_dag4,AF2_dag4,AF3_dag4,AF4_dag4,AF5_dag4,AF6_dag4,AF7_dag4,AF8_dag4,AF9_dag4,AF10_dag4,AF11_dag4,AF12_dag4,AF13_dag4,AF14_dag4,AF15_dag4,AF16_dag4,AF17_dag4,AF18_dag4,AF19_dag4,AF20_dag4,AF21_dag4,AF22_dag4,AF23_dag4,AF24_dag4,AF1_dag5,AF2_dag5,AF3_dag5,AF4_dag5,AF5_dag5,AF6_dag5,AF7_dag5,AF8_dag5,AF9_dag5,AF10_dag5,AF11_dag5,AF12_dag5,AF13_dag5,AF14_dag5,AF15_dag5,AF16_dag5,AF17_dag5,AF18_dag5,AF19_dag5,AF20_dag5,AF21_dag5,AF22_dag5,AF23_dag5,AF24_dag5,AF1_dag6,AF2_dag6,AF3_dag6,AF4_dag6,AF5_dag6,AF6_dag6,AF7_dag6,AF8_dag6,AF9_dag6,AF10_dag6,AF11_dag6,AF12_dag6,AF13_dag6,AF14_dag6,AF15_dag6,AF16_dag6,AF17_dag6,AF18_dag6,AF19_dag6,AF20_dag6,AF21_dag6,AF22_dag6,AF23_dag6,AF24_dag6,AF1_dag7,AF2_dag7,AF3_dag7,AF4_dag7,AF5_dag7,AF6_dag7,AF7_dag7,AF8_dag7,AF9_dag7,AF10_dag7,AF11_dag7,AF12_dag7,AF13_dag7,AF14_dag7,AF15_dag7,AF16_dag7,AF17_dag7,AF18_dag7,AF19_dag7,AF20_dag7,AF21_dag7,AF22_dag7,AF23_dag7,AF24_dag7,AF1_dag8,AF2_dag8,AF3_dag8,AF4_dag8,AF5_dag8,AF6_dag8,AF7_dag8,AF8_dag8,AF9_dag8,AF10_dag8,AF11_dag8,AF12_dag8,AF13_dag8,AF14_dag8,AF15_dag8,AF16_dag8,AF17_dag8,AF18_dag8,AF19_dag8,AF20_dag8,AF21_dag8,AF22_dag8,AF23_dag8,AF24_dag8,AF1_dag9,AF2_dag9,AF3_dag9,AF4_dag9,AF5_dag9,AF6_dag9,AF7_dag9,AF8_dag9,AF9_dag9,AF10_dag9,AF11_dag9,AF12_dag9,AF13_dag9,AF14_dag9,AF15_dag9,AF16_dag9,AF17_dag9,AF18_dag9,AF19_dag9,AF20_dag9,AF21_dag9,AF22_dag9,AF23_dag9,AF24_dag9,AF1_dag10,AF2_dag10,AF3_dag10,AF4_dag10,AF5_dag10,AF6_dag10,AF7_dag10,AF8_dag10,AF9_dag10,AF10_dag10,AF11_dag10,AF12_dag10,AF13_dag10,AF14_dag10,AF15_dag10,AF16_dag10,AF17_dag10,AF18_dag10,AF19_dag10,AF20_dag10,AF21_dag10,AF22_dag10,AF23_dag10,AF24_dag10,AF1_dag11,AF2_dag11,AF3_dag11,AF4_dag11,AF5_dag11,AF6_dag11,AF7_dag11,AF8_dag11,AF9_dag11,AF10_dag11,AF11_dag11,AF12_dag11,AF13_dag11,AF14_dag11,AF15_dag11,AF16_dag11,AF17_dag11,AF18_dag11,AF19_dag11,AF20_dag11,AF21_dag11,AF22_dag11,AF23_dag11,AF24_dag11,AF1_dag12,AF2_dag12,AF3_dag12,AF4_dag12,AF5_dag12,AF6_dag12,AF7_dag12,AF8_dag12,AF9_dag12,AF10_dag12,AF11_dag12,AF12_dag12,AF13_dag12,AF14_dag12,AF15_dag12,AF16_dag12,AF17_dag12,AF18_dag12,AF19_dag12,AF20_dag12,AF21_dag12,AF22_dag12,AF23_dag12,AF24_dag12,AF1_dag13,AF2_dag13,AF3_dag13,AF4_dag13,AF5_dag13,AF6_dag13,AF7_dag13,AF8_dag13,AF9_dag13,AF10_dag13,AF11_dag13,AF12_dag13,AF13_dag13,AF14_dag13,AF15_dag13,AF16_dag13,AF17_dag13,AF18_dag13,AF19_dag13,AF20_dag13,AF21_dag13,AF22_dag13,AF23_dag13,AF24_dag13,AF1_dag14,AF2_dag14,AF3_dag14,AF4_dag14,AF5_dag14,AF6_dag14,AF7_dag14,AF8_dag14,AF9_dag14,AF10_dag14,AF11_dag14,AF12_dag14,AF13_dag14,AF14_dag14,AF15_dag14,AF16_dag14,AF17_dag14,AF18_dag14,AF19_dag14,AF20_dag14,AF21_dag14,AF22_dag14,AF23_dag14,AF24_dag14 FROM OES_ST_V4_VITALS_AF_auto_24"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_AF_man_20'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_af_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,AF1_dag1,AF2_dag1,AF3_dag1,AF4_dag1,AF5_dag1,AF6_dag1,AF7_dag1,AF8_dag1,AF9_dag1,AF10_dag1,AF11_dag1,AF12_dag1,AF13_dag1,AF14_dag1,AF15_dag1,AF16_dag1,AF17_dag1,AF18_dag1,AF19_dag1,AF20_dag1,AF1_dag2,AF2_dag2,AF3_dag2,AF4_dag2,AF5_dag2,AF6_dag2,AF7_dag2,AF8_dag2,AF9_dag2,AF10_dag2,AF11_dag2,AF12_dag2,AF13_dag2,AF14_dag2,AF15_dag2,AF16_dag2,AF17_dag2,AF18_dag2,AF19_dag2,AF20_dag2,AF1_dag3,AF2_dag3,AF3_dag3,AF4_dag3,AF5_dag3,AF6_dag3,AF7_dag3,AF8_dag3,AF9_dag3,AF10_dag3,AF11_dag3,AF12_dag3,AF13_dag3,AF14_dag3,AF15_dag3,AF16_dag3,AF17_dag3,AF18_dag3,AF19_dag3,AF20_dag3,AF1_dag4,AF2_dag4,AF3_dag4,AF4_dag4,AF5_dag4,AF6_dag4,AF7_dag4,AF8_dag4,AF9_dag4,AF10_dag4,AF11_dag4,AF12_dag4,AF13_dag4,AF14_dag4,AF15_dag4,AF16_dag4,AF17_dag4,AF18_dag4,AF19_dag4,AF20_dag4,AF1_dag5,AF2_dag5,AF3_dag5,AF4_dag5,AF5_dag5,AF6_dag5,AF7_dag5,AF8_dag5,AF9_dag5,AF10_dag5,AF11_dag5,AF12_dag5,AF13_dag5,AF14_dag5,AF15_dag5,AF16_dag5,AF17_dag5,AF18_dag5,AF19_dag5,AF20_dag5,AF1_dag6,AF2_dag6,AF3_dag6,AF4_dag6,AF5_dag6,AF6_dag6,AF7_dag6,AF8_dag6,AF9_dag6,AF10_dag6,AF11_dag6,AF12_dag6,AF13_dag6,AF14_dag6,AF15_dag6,AF16_dag6,AF17_dag6,AF18_dag6,AF19_dag6,AF20_dag6,AF1_dag7,AF2_dag7,AF3_dag7,AF4_dag7,AF5_dag7,AF6_dag7,AF7_dag7,AF8_dag7,AF9_dag7,AF10_dag7,AF11_dag7,AF12_dag7,AF13_dag7,AF14_dag7,AF15_dag7,AF16_dag7,AF17_dag7,AF18_dag7,AF19_dag7,AF20_dag7,AF1_dag8,AF2_dag8,AF3_dag8,AF4_dag8,AF5_dag8,AF6_dag8,AF7_dag8,AF8_dag8,AF9_dag8,AF10_dag8,AF11_dag8,AF12_dag8,AF13_dag8,AF14_dag8,AF15_dag8,AF16_dag8,AF17_dag8,AF18_dag8,AF19_dag8,AF20_dag8,AF1_dag9,AF2_dag9,AF3_dag9,AF4_dag9,AF5_dag9,AF6_dag9,AF7_dag9,AF8_dag9,AF9_dag9,AF10_dag9,AF11_dag9,AF12_dag9,AF13_dag9,AF14_dag9,AF15_dag9,AF16_dag9,AF17_dag9,AF18_dag9,AF19_dag9,AF20_dag9,AF1_dag10,AF2_dag10,AF3_dag10,AF4_dag10,AF5_dag10,AF6_dag10,AF7_dag10,AF8_dag10,AF9_dag10,AF10_dag10,AF11_dag10,AF12_dag10,AF13_dag10,AF14_dag10,AF15_dag10,AF16_dag10,AF17_dag10,AF18_dag10,AF19_dag10,AF20_dag10,AF1_dag11,AF2_dag11,AF3_dag11,AF4_dag11,AF5_dag11,AF6_dag11,AF7_dag11,AF8_dag11,AF9_dag11,AF10_dag11,AF11_dag11,AF12_dag11,AF13_dag11,AF14_dag11,AF15_dag11,AF16_dag11,AF17_dag11,AF18_dag11,AF19_dag11,AF20_dag11,AF1_dag12,AF2_dag12,AF3_dag12,AF4_dag12,AF5_dag12,AF6_dag12,AF7_dag12,AF8_dag12,AF9_dag12,AF10_dag12,AF11_dag12,AF12_dag12,AF13_dag12,AF14_dag12,AF15_dag12,AF16_dag12,AF17_dag12,AF18_dag12,AF19_dag12,AF20_dag12,AF1_dag13,AF2_dag13,AF3_dag13,AF4_dag13,AF5_dag13,AF6_dag13,AF7_dag13,AF8_dag13,AF9_dag13,AF10_dag13,AF11_dag13,AF12_dag13,AF13_dag13,AF14_dag13,AF15_dag13,AF16_dag13,AF17_dag13,AF18_dag13,AF19_dag13,AF20_dag13,AF1_dag14,AF2_dag14,AF3_dag14,AF4_dag14,AF5_dag14,AF6_dag14,AF7_dag14,AF8_dag14,AF9_dag14,AF10_dag14,AF11_dag14,AF12_dag14,AF13_dag14,AF14_dag14,AF15_dag14,AF16_dag14,AF17_dag14,AF18_dag14,AF19_dag14,AF20_dag14 FROM OES_ST_V4_VITALS_AF_man_20"))
```

## VITALS HF
```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_HF_HR_Auto_24'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_hf_hr_auto <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,HF1_dag1,HF2_dag1,HF3_dag1,HF4_dag1,HF5_dag1,HF6_dag1,HF7_dag1,HF8_dag1,HF9_dag1,HF10_dag1,HF11_dag1,HF12_dag1,HF13_dag1,HF14_dag1,HF15_dag1,HF16_dag1,HF17_dag1,HF18_dag1,HF19_dag1,HF20_dag1,HF21_dag1,HF22_dag1,HF23_dag1,HF24_dag1,HF1_dag2,HF2_dag2,HF3_dag2,HF4_dag2,HF5_dag2,HF6_dag2,HF7_dag2,HF8_dag2,HF9_dag2,HF10_dag2,HF11_dag2,HF12_dag2,HF13_dag2,HF14_dag2,HF15_dag2,HF16_dag2,HF17_dag2,HF18_dag2,HF19_dag2,HF20_dag2,HF21_dag2,HF22_dag2,HF23_dag2,HF24_dag2,HF1_dag3,HF2_dag3,HF3_dag3,HF4_dag3,HF5_dag3,HF6_dag3,HF7_dag3,HF8_dag3,HF9_dag3,HF10_dag3,HF11_dag3,HF12_dag3,HF13_dag3,HF14_dag3,HF15_dag3,HF16_dag3,HF17_dag3,HF18_dag3,HF19_dag3,HF20_dag3,HF21_dag3,HF22_dag3,HF23_dag3,HF24_dag3,HF1_dag4,HF2_dag4,HF3_dag4,HF4_dag4,HF5_dag4,HF6_dag4,HF7_dag4,HF8_dag4,HF9_dag4,HF10_dag4,HF11_dag4,HF12_dag4,HF13_dag4,HF14_dag4,HF15_dag4,HF16_dag4,HF17_dag4,HF18_dag4,HF19_dag4,HF20_dag4,HF21_dag4,HF22_dag4,HF23_dag4,HF24_dag4,HF1_dag5,HF2_dag5,HF3_dag5,HF4_dag5,HF5_dag5,HF6_dag5,HF7_dag5,HF8_dag5,HF9_dag5,HF10_dag5,HF11_dag5,HF12_dag5,HF13_dag5,HF14_dag5,HF15_dag5,HF16_dag5,HF17_dag5,HF18_dag5,HF19_dag5,HF20_dag5,HF21_dag5,HF22_dag5,HF23_dag5,HF24_dag5,HF1_dag6,HF2_dag6,HF3_dag6,HF4_dag6,HF5_dag6,HF6_dag6,HF7_dag6,HF8_dag6,HF9_dag6,HF10_dag6,HF11_dag6,HF12_dag6,HF13_dag6,HF14_dag6,HF15_dag6,HF16_dag6,HF17_dag6,HF18_dag6,HF19_dag6,HF20_dag6,HF21_dag6,HF22_dag6,HF23_dag6,HF24_dag6,HF1_dag7,HF2_dag7,HF3_dag7,HF4_dag7,HF5_dag7,HF6_dag7,HF7_dag7,HF8_dag7,HF9_dag7,HF10_dag7,HF11_dag7,HF12_dag7,HF13_dag7,HF14_dag7,HF15_dag7,HF16_dag7,HF17_dag7,HF18_dag7,HF19_dag7,HF20_dag7,HF21_dag7,HF22_dag7,HF23_dag7,HF24_dag7,HF1_dag8,HF2_dag8,HF3_dag8,HF4_dag8,HF5_dag8,HF6_dag8,HF7_dag8,HF8_dag8,HF9_dag8,HF10_dag8,HF11_dag8,HF12_dag8,HF13_dag8,HF14_dag8,HF15_dag8,HF16_dag8,HF17_dag8,HF18_dag8,HF19_dag8,HF20_dag8,HF21_dag8,HF22_dag8,HF23_dag8,HF24_dag8,HF1_dag9,HF2_dag9,HF3_dag9,HF4_dag9,HF5_dag9,HF6_dag9,HF7_dag9,HF8_dag9,HF9_dag9,HF10_dag9,HF11_dag9,HF12_dag9,HF13_dag9,HF14_dag9,HF15_dag9,HF16_dag9,HF17_dag9,HF18_dag9,HF19_dag9,HF20_dag9,HF21_dag9,HF22_dag9,HF23_dag9,HF24_dag9,HF1_dag10,HF2_dag10,HF3_dag10,HF4_dag10,HF5_dag10,HF6_dag10,HF7_dag10,HF8_dag10,HF9_dag10,HF10_dag10,HF11_dag10,HF12_dag10,HF13_dag10,HF14_dag10,HF15_dag10,HF16_dag10,HF17_dag10,HF18_dag10,HF19_dag10,HF20_dag10,HF21_dag10,HF22_dag10,HF23_dag10,HF24_dag10,HF1_dag11,HF2_dag11,HF3_dag11,HF4_dag11,HF5_dag11,HF6_dag11,HF7_dag11,HF8_dag11,HF9_dag11,HF10_dag11,HF11_dag11,HF12_dag11,HF13_dag11,HF14_dag11,HF15_dag11,HF16_dag11,HF17_dag11,HF18_dag11,HF19_dag11,HF20_dag11,HF21_dag11,HF22_dag11,HF23_dag11,HF24_dag11,HF1_dag12,HF2_dag12,HF3_dag12,HF4_dag12,HF5_dag12,HF6_dag12,HF7_dag12,HF8_dag12,HF9_dag12,HF10_dag12,HF11_dag12,HF12_dag12,HF13_dag12,HF14_dag12,HF15_dag12,HF16_dag12,HF17_dag12,HF18_dag12,HF19_dag12,HF20_dag12,HF21_dag12,HF22_dag12,HF23_dag12,HF24_dag12 FROM OES_ST_V4_VITALS_HF_HR_Auto_24"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_HF_HR_man_20'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_hf_hr_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,HF1_dag1,HF2_dag1,HF3_dag1,HF4_dag1,HF5_dag1,HF6_dag1,HF7_dag1,HF8_dag1,HF9_dag1,HF10_dag1,HF11_dag1,HF12_dag1,HF13_dag1,HF14_dag1,HF15_dag1,HF16_dag1,HF17_dag1,HF18_dag1,HF19_dag1,HF20_dag1,HF1_dag2,HF2_dag2,HF3_dag2,HF4_dag2,HF5_dag2,HF6_dag2,HF7_dag2,HF8_dag2,HF9_dag2,HF10_dag2,HF11_dag2,HF12_dag2,HF13_dag2,HF14_dag2,HF15_dag2,HF16_dag2,HF17_dag2,HF18_dag2,HF19_dag2,HF20_dag2,HF1_dag3,HF2_dag3,HF3_dag3,HF4_dag3,HF5_dag3,HF6_dag3,HF7_dag3,HF8_dag3,HF9_dag3,HF10_dag3,HF11_dag3,HF12_dag3,HF13_dag3,HF14_dag3,HF15_dag3,HF16_dag3,HF17_dag3,HF18_dag3,HF19_dag3,HF20_dag3,HF1_dag4,HF2_dag4,HF3_dag4,HF4_dag4,HF5_dag4,HF6_dag4,HF7_dag4,HF8_dag4,HF9_dag4,HF10_dag4,HF11_dag4,HF12_dag4,HF13_dag4,HF14_dag4,HF15_dag4,HF16_dag4,HF17_dag4,HF18_dag4,HF19_dag4,HF20_dag4,HF1_dag5,HF2_dag5,HF3_dag5,HF4_dag5,HF5_dag5,HF6_dag5,HF7_dag5,HF8_dag5,HF9_dag5,HF10_dag5,HF11_dag5,HF12_dag5,HF13_dag5,HF14_dag5,HF15_dag5,HF16_dag5,HF17_dag5,HF18_dag5,HF19_dag5,HF20_dag5,HF1_dag6,HF2_dag6,HF3_dag6,HF4_dag6,HF5_dag6,HF6_dag6,HF7_dag6,HF8_dag6,HF9_dag6,HF10_dag6,HF11_dag6,HF12_dag6,HF13_dag6,HF14_dag6,HF15_dag6,HF16_dag6,HF17_dag6,HF18_dag6,HF19_dag6,HF20_dag6,HF1_dag7,HF2_dag7,HF3_dag7,HF4_dag7,HF5_dag7,HF6_dag7,HF7_dag7,HF8_dag7,HF9_dag7,HF10_dag7,HF11_dag7,HF12_dag7,HF13_dag7,HF14_dag7,HF15_dag7,HF16_dag7,HF17_dag7,HF18_dag7,HF19_dag7,HF20_dag7,HF1_dag8,HF2_dag8,HF3_dag8,HF4_dag8,HF5_dag8,HF6_dag8,HF7_dag8,HF8_dag8,HF9_dag8,HF10_dag8,HF11_dag8,HF12_dag8,HF13_dag8,HF14_dag8,HF15_dag8,HF16_dag8,HF17_dag8,HF18_dag8,HF19_dag8,HF20_dag8,HF1_dag9,HF2_dag9,HF3_dag9,HF4_dag9,HF5_dag9,HF6_dag9,HF7_dag9,HF8_dag9,HF9_dag9,HF10_dag9,HF11_dag9,HF12_dag9,HF13_dag9,HF14_dag9,HF15_dag9,HF16_dag9,HF17_dag9,HF18_dag9,HF19_dag9,HF20_dag9,HF1_dag10,HF2_dag10,HF3_dag10,HF4_dag10,HF5_dag10,HF6_dag10,HF7_dag10,HF8_dag10,HF9_dag10,HF10_dag10,HF11_dag10,HF12_dag10,HF13_dag10,HF14_dag10,HF15_dag10,HF16_dag10,HF17_dag10,HF18_dag10,HF19_dag10,HF20_dag10,HF1_dag11,HF2_dag11,HF3_dag11,HF4_dag11,HF5_dag11,HF6_dag11,HF7_dag11,HF8_dag11,HF9_dag11,HF10_dag11,HF11_dag11,HF12_dag11,HF13_dag11,HF14_dag11,HF15_dag11,HF16_dag11,HF17_dag11,HF18_dag11,HF19_dag11,HF20_dag11,HF1_dag12,HF2_dag12,HF3_dag12,HF4_dag12,HF5_dag12,HF6_dag12,HF7_dag12,HF8_dag12,HF9_dag12,HF10_dag12,HF11_dag12,HF12_dag12,HF13_dag12,HF14_dag12,HF15_dag12,HF16_dag12,HF17_dag12,HF18_dag12,HF19_dag12,HF20_dag12,HF1_dag13,HF2_dag13,HF3_dag13,HF4_dag13,HF5_dag13,HF6_dag13,HF7_dag13,HF8_dag13,HF9_dag13,HF10_dag13,HF11_dag13,HF12_dag13,HF13_dag13,HF14_dag13,HF15_dag13,HF16_dag13,HF17_dag13,HF18_dag13,HF19_dag13,HF20_dag13,HF1_dag14,HF2_dag14,HF3_dag14,HF4_dag14,HF5_dag14,HF6_dag14,HF7_dag14,HF8_dag14,HF9_dag14,HF10_dag14,HF11_dag14,HF12_dag14,HF13_dag14,HF14_dag14,HF15_dag14,HF16_dag14,HF17_dag14,HF18_dag14,HF19_dag14,HF20_dag14 FROM OES_ST_V4_VITALS_HF_HR_man_20"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_HF_PR_man_15'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_hf_pr_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,HF1_dag1,HF2_dag1,HF3_dag1,HF4_dag1,HF5_dag1,HF6_dag1,HF7_dag1,HF8_dag1,HF9_dag1,HF10_dag1,HF11_dag1,HF12_dag1,HF13_dag1,HF14_dag1,HF15_dag1,HF1_dag2,HF2_dag2,HF3_dag2,HF4_dag2,HF5_dag2,HF6_dag2,HF7_dag2,HF8_dag2,HF9_dag2,HF10_dag2,HF11_dag2,HF12_dag2,HF13_dag2,HF14_dag2,HF15_dag2,HF1_dag3,HF2_dag3,HF3_dag3,HF4_dag3,HF5_dag3,HF6_dag3,HF7_dag3,HF8_dag3,HF9_dag3,HF10_dag3,HF11_dag3,HF12_dag3,HF13_dag3,HF14_dag3,HF15_dag3,HF1_dag4,HF2_dag4,HF3_dag4,HF4_dag4,HF5_dag4,HF6_dag4,HF7_dag4,HF8_dag4,HF9_dag4,HF10_dag4,HF11_dag4,HF12_dag4,HF13_dag4,HF14_dag4,HF15_dag4,HF1_dag5,HF2_dag5,HF3_dag5,HF4_dag5,HF5_dag5,HF6_dag5,HF7_dag5,HF8_dag5,HF9_dag5,HF10_dag5,HF11_dag5,HF12_dag5,HF13_dag5,HF14_dag5,HF15_dag5,HF1_dag6,HF2_dag6,HF3_dag6,HF4_dag6,HF5_dag6,HF6_dag6,HF7_dag6,HF8_dag6,HF9_dag6,HF10_dag6,HF11_dag6,HF12_dag6,HF13_dag6,HF14_dag6,HF15_dag6,HF1_dag7,HF2_dag7,HF3_dag7,HF4_dag7,HF5_dag7,HF6_dag7,HF7_dag7,HF8_dag7,HF9_dag7,HF10_dag7,HF11_dag7,HF12_dag7,HF13_dag7,HF14_dag7,HF15_dag7,HF1_dag8,HF2_dag8,HF3_dag8,HF4_dag8,HF5_dag8,HF6_dag8,HF7_dag8,HF8_dag8,HF9_dag8,HF10_dag8,HF11_dag8,HF12_dag8,HF13_dag8,HF14_dag8,HF15_dag8,HF1_dag9,HF2_dag9,HF3_dag9,HF4_dag9,HF5_dag9,HF6_dag9,HF7_dag9,HF8_dag9,HF9_dag9,HF10_dag9,HF11_dag9,HF12_dag9,HF13_dag9,HF14_dag9,HF15_dag9,HF1_dag10,HF2_dag10,HF3_dag10,HF4_dag10,HF5_dag10,HF6_dag10,HF7_dag10,HF8_dag10,HF9_dag10,HF10_dag10,HF11_dag10,HF12_dag10,HF13_dag10,HF14_dag10,HF15_dag10,HF1_dag11,HF2_dag11,HF3_dag11,HF4_dag11,HF5_dag11,HF6_dag11,HF7_dag11,HF8_dag11,HF9_dag11,HF10_dag11,HF11_dag11,HF12_dag11,HF13_dag11,HF14_dag11,HF15_dag11,HF1_dag12,HF2_dag12,HF3_dag12,HF4_dag12,HF5_dag12,HF6_dag12,HF7_dag12,HF8_dag12,HF9_dag12,HF10_dag12,HF11_dag12,HF12_dag12,HF13_dag12,HF14_dag12,HF15_dag12,HF1_dag13,HF2_dag13,HF3_dag13,HF4_dag13,HF5_dag13,HF6_dag13,HF7_dag13,HF8_dag13,HF9_dag13,HF10_dag13,HF11_dag13,HF12_dag13,HF13_dag13,HF14_dag13,HF15_dag13,HF1_dag14,HF2_dag14,HF3_dag14,HF4_dag14,HF5_dag14,HF6_dag14,HF7_dag14,HF8_dag14,HF9_dag14,HF10_dag14,HF11_dag14,HF12_dag14,HF13_dag14,HF14_dag14,HF15_dag14 FROM OES_ST_V4_VITALS_HF_PR_man_15"))
```

## RR
```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_RRsys_auto_24'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_rr_auto <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,RRsys1_dag1,RRsys2_dag1,RRsys3_dag1,RRsys4_dag1,RRsys5_dag1,RRsys6_dag1,RRsys7_dag1,RRsys8_dag1,RRsys9_dag1,RRsys10_dag1,RRsys11_dag1,RRsys12_dag1,RRsys13_dag1,RRsys14_dag1,RRsys15_dag1,RRsys16_dag1,RRsys17_dag1,RRsys18_dag1,RRsys19_dag1,RRsys20_dag1,RRsys21_dag1,RRsys22_dag1,RRsys23_dag1,RRsys24_dag1,RRsys1_dag2,RRsys2_dag2,RRsys3_dag2,RRsys4_dag2,RRsys5_dag2,RRsys6_dag2,RRsys7_dag2,RRsys8_dag2,RRsys9_dag2,RRsys10_dag2,RRsys11_dag2,RRsys12_dag2,RRsys13_dag2,RRsys14_dag2,RRsys15_dag2,RRsys16_dag2,RRsys17_dag2,RRsys18_dag2,RRsys19_dag2,RRsys20_dag2,RRsys21_dag2,RRsys22_dag2,RRsys23_dag2,RRsys24_dag2,RRsys1_dag3,RRsys2_dag3,RRsys3_dag3,RRsys4_dag3,RRsys5_dag3,RRsys6_dag3,RRsys7_dag3,RRsys8_dag3,RRsys9_dag3,RRsys10_dag3,RRsys11_dag3,RRsys12_dag3,RRsys13_dag3,RRsys14_dag3,RRsys15_dag3,RRsys16_dag3,RRsys17_dag3,RRsys18_dag3,RRsys19_dag3,RRsys20_dag3,RRsys21_dag3,RRsys22_dag3,RRsys23_dag3,RRsys24_dag3,RRsys1_dag4,RRsys2_dag4,RRsys3_dag4,RRsys4_dag4,RRsys5_dag4,RRsys6_dag4,RRsys7_dag4,RRsys8_dag4,RRsys9_dag4,RRsys10_dag4,RRsys11_dag4,RRsys12_dag4,RRsys13_dag4,RRsys14_dag4,RRsys15_dag4,RRsys16_dag4,RRsys17_dag4,RRsys18_dag4,RRsys19_dag4,RRsys20_dag4,RRsys21_dag4,RRsys22_dag4,RRsys23_dag4,RRsys24_dag4,RRsys1_dag5,RRsys2_dag5,RRsys3_dag5,RRsys4_dag5,RRsys5_dag5,RRsys6_dag5,RRsys7_dag5,RRsys8_dag5,RRsys9_dag5,RRsys10_dag5,RRsys11_dag5,RRsys12_dag5,RRsys13_dag5,RRsys14_dag5,RRsys15_dag5,RRsys16_dag5,RRsys17_dag5,RRsys18_dag5,RRsys19_dag5,RRsys20_dag5,RRsys21_dag5,RRsys22_dag5,RRsys23_dag5,RRsys24_dag5,RRsys1_dag6,RRsys2_dag6,RRsys3_dag6,RRsys4_dag6,RRsys5_dag6,RRsys6_dag6,RRsys7_dag6,RRsys8_dag6,RRsys9_dag6,RRsys10_dag6,RRsys11_dag6,RRsys12_dag6,RRsys13_dag6,RRsys14_dag6,RRsys15_dag6,RRsys16_dag6,RRsys17_dag6,RRsys18_dag6,RRsys19_dag6,RRsys20_dag6,RRsys21_dag6,RRsys22_dag6,RRsys23_dag6,RRsys24_dag6,RRsys1_dag7,RRsys2_dag7,RRsys3_dag7,RRsys4_dag7,RRsys5_dag7,RRsys6_dag7,RRsys7_dag7,RRsys8_dag7,RRsys9_dag7,RRsys10_dag7,RRsys11_dag7,RRsys12_dag7,RRsys13_dag7,RRsys14_dag7,RRsys15_dag7,RRsys16_dag7,RRsys17_dag7,RRsys18_dag7,RRsys19_dag7,RRsys20_dag7,RRsys21_dag7,RRsys22_dag7,RRsys23_dag7,RRsys24_dag7,RRsys1_dag8,RRsys2_dag8,RRsys3_dag8,RRsys4_dag8,RRsys5_dag8,RRsys6_dag8,RRsys7_dag8,RRsys8_dag8,RRsys9_dag8,RRsys10_dag8,RRsys11_dag8,RRsys12_dag8,RRsys13_dag8,RRsys14_dag8,RRsys15_dag8,RRsys16_dag8,RRsys17_dag8,RRsys18_dag8,RRsys19_dag8,RRsys20_dag8,RRsys21_dag8,RRsys22_dag8,RRsys23_dag8,RRsys24_dag8,RRsys1_dag9,RRsys2_dag9,RRsys3_dag9,RRsys4_dag9,RRsys5_dag9,RRsys6_dag9,RRsys7_dag9,RRsys8_dag9,RRsys9_dag9,RRsys10_dag9,RRsys11_dag9,RRsys12_dag9,RRsys13_dag9,RRsys14_dag9,RRsys15_dag9,RRsys16_dag9,RRsys17_dag9,RRsys18_dag9,RRsys19_dag9,RRsys20_dag9,RRsys21_dag9,RRsys22_dag9,RRsys23_dag9,RRsys24_dag9,RRsys1_dag10,RRsys2_dag10,RRsys3_dag10,RRsys4_dag10,RRsys5_dag10,RRsys6_dag10,RRsys7_dag10,RRsys8_dag10,RRsys9_dag10,RRsys10_dag10,RRsys11_dag10,RRsys12_dag10,RRsys13_dag10,RRsys14_dag10,RRsys15_dag10,RRsys16_dag10,RRsys17_dag10,RRsys18_dag10,RRsys19_dag10,RRsys20_dag10,RRsys21_dag10,RRsys22_dag10,RRsys23_dag10,RRsys24_dag10,RRsys1_dag11,RRsys2_dag11,RRsys3_dag11,RRsys4_dag11,RRsys5_dag11,RRsys6_dag11,RRsys7_dag11,RRsys8_dag11,RRsys9_dag11,RRsys10_dag11,RRsys11_dag11,RRsys12_dag11,RRsys13_dag11,RRsys14_dag11,RRsys15_dag11,RRsys16_dag11,RRsys17_dag11,RRsys18_dag11,RRsys19_dag11,RRsys20_dag11,RRsys21_dag11,RRsys22_dag11,RRsys23_dag11,RRsys24_dag11,RRsys1_dag12,RRsys2_dag12,RRsys3_dag12,RRsys4_dag12,RRsys5_dag12,RRsys6_dag12,RRsys7_dag12,RRsys8_dag12,RRsys9_dag12,RRsys10_dag12,RRsys11_dag12,RRsys12_dag12,RRsys13_dag12,RRsys14_dag12,RRsys15_dag12,RRsys16_dag12,RRsys17_dag12,RRsys18_dag12,RRsys19_dag12,RRsys20_dag12,RRsys21_dag12,RRsys22_dag12,RRsys23_dag12,RRsys24_dag12 FROM OES_ST_V4_VITALS_RRsys_auto_24"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_RRsys_man_20'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_rr_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,RRsys1_dag1,RRsys2_dag1,RRsys3_dag1,RRsys4_dag1,RRsys5_dag1,RRsys6_dag1,RRsys7_dag1,RRsys8_dag1,RRsys9_dag1,RRsys10_dag1,RRsys11_dag1,RRsys12_dag1,RRsys13_dag1,RRsys14_dag1,RRsys15_dag1,RRsys16_dag1,RRsys17_dag1,RRsys18_dag1,RRsys19_dag1,RRsys20_dag1,RRsys1_dag2,RRsys2_dag2,RRsys3_dag2,RRsys4_dag2,RRsys5_dag2,RRsys6_dag2,RRsys7_dag2,RRsys8_dag2,RRsys9_dag2,RRsys10_dag2,RRsys11_dag2,RRsys12_dag2,RRsys13_dag2,RRsys14_dag2,RRsys15_dag2,RRsys16_dag2,RRsys17_dag2,RRsys18_dag2,RRsys19_dag2,RRsys20_dag2,RRsys1_dag3,RRsys2_dag3,RRsys3_dag3,RRsys4_dag3,RRsys5_dag3,RRsys6_dag3,RRsys7_dag3,RRsys8_dag3,RRsys9_dag3,RRsys10_dag3,RRsys11_dag3,RRsys12_dag3,RRsys13_dag3,RRsys14_dag3,RRsys15_dag3,RRsys16_dag3,RRsys17_dag3,RRsys18_dag3,RRsys19_dag3,RRsys20_dag3,RRsys1_dag4,RRsys2_dag4,RRsys3_dag4,RRsys4_dag4,RRsys5_dag4,RRsys6_dag4,RRsys7_dag4,RRsys8_dag4,RRsys9_dag4,RRsys10_dag4,RRsys11_dag4,RRsys12_dag4,RRsys13_dag4,RRsys14_dag4,RRsys15_dag4,RRsys16_dag4,RRsys17_dag4,RRsys18_dag4,RRsys19_dag4,RRsys20_dag4,RRsys1_dag5,RRsys2_dag5,RRsys3_dag5,RRsys4_dag5,RRsys5_dag5,RRsys6_dag5,RRsys7_dag5,RRsys8_dag5,RRsys9_dag5,RRsys10_dag5,RRsys11_dag5,RRsys12_dag5,RRsys13_dag5,RRsys14_dag5,RRsys15_dag5,RRsys16_dag5,RRsys17_dag5,RRsys18_dag5,RRsys19_dag5,RRsys20_dag5,RRsys1_dag6,RRsys2_dag6,RRsys3_dag6,RRsys4_dag6,RRsys5_dag6,RRsys6_dag6,RRsys7_dag6,RRsys8_dag6,RRsys9_dag6,RRsys10_dag6,RRsys11_dag6,RRsys12_dag6,RRsys13_dag6,RRsys14_dag6,RRsys15_dag6,RRsys16_dag6,RRsys17_dag6,RRsys18_dag6,RRsys19_dag6,RRsys20_dag6,RRsys1_dag7,RRsys2_dag7,RRsys3_dag7,RRsys4_dag7,RRsys5_dag7,RRsys6_dag7,RRsys7_dag7,RRsys8_dag7,RRsys9_dag7,RRsys10_dag7,RRsys11_dag7,RRsys12_dag7,RRsys13_dag7,RRsys14_dag7,RRsys15_dag7,RRsys16_dag7,RRsys17_dag7,RRsys18_dag7,RRsys19_dag7,RRsys20_dag7,RRsys1_dag8,RRsys2_dag8,RRsys3_dag8,RRsys4_dag8,RRsys5_dag8,RRsys6_dag8,RRsys7_dag8,RRsys8_dag8,RRsys9_dag8,RRsys10_dag8,RRsys11_dag8,RRsys12_dag8,RRsys13_dag8,RRsys14_dag8,RRsys15_dag8,RRsys16_dag8,RRsys17_dag8,RRsys18_dag8,RRsys19_dag8,RRsys20_dag8,RRsys1_dag9,RRsys2_dag9,RRsys3_dag9,RRsys4_dag9,RRsys5_dag9,RRsys6_dag9,RRsys7_dag9,RRsys8_dag9,RRsys9_dag9,RRsys10_dag9,RRsys11_dag9,RRsys12_dag9,RRsys13_dag9,RRsys14_dag9,RRsys15_dag9,RRsys16_dag9,RRsys17_dag9,RRsys18_dag9,RRsys19_dag9,RRsys20_dag9,RRsys1_dag10,RRsys2_dag10,RRsys3_dag10,RRsys4_dag10,RRsys5_dag10,RRsys6_dag10,RRsys7_dag10,RRsys8_dag10,RRsys9_dag10,RRsys10_dag10,RRsys11_dag10,RRsys12_dag10,RRsys13_dag10,RRsys14_dag10,RRsys15_dag10,RRsys16_dag10,RRsys17_dag10,RRsys18_dag10,RRsys19_dag10,RRsys20_dag10,RRsys1_dag11,RRsys2_dag11,RRsys3_dag11,RRsys4_dag11,RRsys5_dag11,RRsys6_dag11,RRsys7_dag11,RRsys8_dag11,RRsys9_dag11,RRsys10_dag11,RRsys11_dag11,RRsys12_dag11,RRsys13_dag11,RRsys14_dag11,RRsys15_dag11,RRsys16_dag11,RRsys17_dag11,RRsys18_dag11,RRsys19_dag11,RRsys20_dag11,RRsys1_dag12,RRsys2_dag12,RRsys3_dag12,RRsys4_dag12,RRsys5_dag12,RRsys6_dag12,RRsys7_dag12,RRsys8_dag12,RRsys9_dag12,RRsys10_dag12,RRsys11_dag12,RRsys12_dag12,RRsys13_dag12,RRsys14_dag12,RRsys15_dag12,RRsys16_dag12,RRsys17_dag12,RRsys18_dag12,RRsys19_dag12,RRsys20_dag12,RRsys1_dag13,RRsys2_dag13,RRsys3_dag13,RRsys4_dag13,RRsys5_dag13,RRsys6_dag13,RRsys7_dag13,RRsys8_dag13,RRsys9_dag13,RRsys10_dag13,RRsys11_dag13,RRsys12_dag13,RRsys13_dag13,RRsys14_dag13,RRsys15_dag13,RRsys16_dag13,RRsys17_dag13,RRsys18_dag13,RRsys19_dag13,RRsys20_dag13,RRsys1_dag14,RRsys2_dag14,RRsys3_dag14,RRsys4_dag14,RRsys5_dag14,RRsys6_dag14,RRsys7_dag14,RRsys8_dag14,RRsys9_dag14,RRsys10_dag14,RRsys11_dag14,RRsys12_dag14,RRsys13_dag14,RRsys14_dag14,RRsys15_dag14,RRsys16_dag14,RRsys17_dag14,RRsys18_dag14,RRsys19_dag14,RRsys20_dag14 FROM OES_ST_V4_VITALS_RRsys_man_20"))
```

## temp
```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_temp_auto_24'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_temp_auto <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,temp1_dag1,temp2_dag1,temp3_dag1,temp4_dag1,temp5_dag1,temp6_dag1,temp7_dag1,temp8_dag1,temp9_dag1,temp10_dag1,temp11_dag1,temp12_dag1,temp13_dag1,temp14_dag1,temp15_dag1,temp16_dag1,temp17_dag1,temp18_dag1,temp19_dag1,temp20_dag1,temp21_dag1,temp22_dag1,temp23_dag1,temp24_dag1,temp1_dag2,temp2_dag2,temp3_dag2,temp4_dag2,temp5_dag2,temp6_dag2,temp7_dag2,temp8_dag2,temp9_dag2,temp10_dag2,temp11_dag2,temp12_dag2,temp13_dag2,temp14_dag2,temp15_dag2,temp16_dag2,temp17_dag2,temp18_dag2,temp19_dag2,temp20_dag2,temp21_dag2,temp22_dag2,temp23_dag2,temp24_dag2,temp1_dag3,temp2_dag3,temp3_dag3,temp4_dag3,temp5_dag3,temp6_dag3,temp7_dag3,temp8_dag3,temp9_dag3,temp10_dag3,temp11_dag3,temp12_dag3,temp13_dag3,temp14_dag3,temp15_dag3,temp16_dag3,temp17_dag3,temp18_dag3,temp19_dag3,temp20_dag3,temp21_dag3,temp22_dag3,temp23_dag3,temp24_dag3,temp1_dag4,temp2_dag4,temp3_dag4,temp4_dag4,temp5_dag4,temp6_dag4,temp7_dag4,temp8_dag4,temp9_dag4,temp10_dag4,temp11_dag4,temp12_dag4,temp13_dag4,temp14_dag4,temp15_dag4,temp16_dag4,temp17_dag4,temp18_dag4,temp19_dag4,temp20_dag4,temp21_dag4,temp22_dag4,temp23_dag4,temp24_dag4,temp1_dag5,temp2_dag5,temp3_dag5,temp4_dag5,temp5_dag5,temp6_dag5,temp7_dag5,temp8_dag5,temp9_dag5,temp10_dag5,temp11_dag5,temp12_dag5,temp13_dag5,temp14_dag5,temp15_dag5,temp16_dag5,temp17_dag5,temp18_dag5,temp19_dag5,temp20_dag5,temp21_dag5,temp22_dag5,temp23_dag5,temp24_dag5,temp1_dag6,temp2_dag6,temp3_dag6,temp4_dag6,temp5_dag6,temp6_dag6,temp7_dag6,temp8_dag6,temp9_dag6,temp10_dag6,temp11_dag6,temp12_dag6,temp13_dag6,temp14_dag6,temp15_dag6,temp16_dag6,temp17_dag6,temp18_dag6,temp19_dag6,temp20_dag6,temp21_dag6,temp22_dag6,temp23_dag6,temp24_dag6,temp1_dag7,temp2_dag7,temp3_dag7,temp4_dag7,temp5_dag7,temp6_dag7,temp7_dag7,temp8_dag7,temp9_dag7,temp10_dag7,temp11_dag7,temp12_dag7,temp13_dag7,temp14_dag7,temp15_dag7,temp16_dag7,temp17_dag7,temp18_dag7,temp19_dag7,temp20_dag7,temp21_dag7,temp22_dag7,temp23_dag7,temp24_dag7,temp1_dag8,temp2_dag8,temp3_dag8,temp4_dag8,temp5_dag8,temp6_dag8,temp7_dag8,temp8_dag8,temp9_dag8,temp10_dag8,temp11_dag8,temp12_dag8,temp13_dag8,temp14_dag8,temp15_dag8,temp16_dag8,temp17_dag8,temp18_dag8,temp19_dag8,temp20_dag8,temp21_dag8,temp22_dag8,temp23_dag8,temp24_dag8,temp1_dag9,temp2_dag9,temp3_dag9,temp4_dag9,temp5_dag9,temp6_dag9,temp7_dag9,temp8_dag9,temp9_dag9,temp10_dag9,temp11_dag9,temp12_dag9,temp13_dag9,temp14_dag9,temp15_dag9,temp16_dag9,temp17_dag9,temp18_dag9,temp19_dag9,temp20_dag9,temp21_dag9,temp22_dag9,temp23_dag9,temp24_dag9,temp1_dag10,temp2_dag10,temp3_dag10,temp4_dag10,temp5_dag10,temp6_dag10,temp7_dag10,temp8_dag10,temp9_dag10,temp10_dag10,temp11_dag10,temp12_dag10,temp13_dag10,temp14_dag10,temp15_dag10,temp16_dag10,temp17_dag10,temp18_dag10,temp19_dag10,temp20_dag10,temp21_dag10,temp22_dag10,temp23_dag10,temp24_dag10,temp1_dag11,temp2_dag11,temp3_dag11,temp4_dag11,temp5_dag11,temp6_dag11,temp7_dag11,temp8_dag11,temp9_dag11,temp10_dag11,temp11_dag11,temp12_dag11,temp13_dag11,temp14_dag11,temp15_dag11,temp16_dag11,temp17_dag11,temp18_dag11,temp19_dag11,temp20_dag11,temp21_dag11,temp22_dag11,temp23_dag11,temp24_dag11,temp1_dag12,temp2_dag12,temp3_dag12,temp4_dag12,temp5_dag12,temp6_dag12,temp7_dag12,temp8_dag12,temp9_dag12,temp10_dag12,temp11_dag12,temp12_dag12,temp13_dag12,temp14_dag12,temp15_dag12,temp16_dag12,temp17_dag12,temp18_dag12,temp19_dag12,temp20_dag12,temp21_dag12,temp22_dag12,temp23_dag12,temp24_dag12 FROM OES_ST_V4_VITALS_temp_auto_24"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VITALS_temp_man_20'")$COLUMN_NAME), collapse = ",")
#columns_string

vitals_temp_man <- as.data.frame(dbGetQuery(con, "SELECT Case_number,Datum_operatie_nieuw,Pt_nummer,temp1_dag1,temp2_dag1,temp3_dag1,temp4_dag1,temp5_dag1,temp6_dag1,temp7_dag1,temp8_dag1,temp9_dag1,temp10_dag1,temp11_dag1,temp12_dag1,temp13_dag1,temp14_dag1,temp15_dag1,temp16_dag1,temp17_dag1,temp18_dag1,temp19_dag1,temp20_dag1,temp1_dag2,temp2_dag2,temp3_dag2,temp4_dag2,temp5_dag2,temp6_dag2,temp7_dag2,temp8_dag2,temp9_dag2,temp10_dag2,temp11_dag2,temp12_dag2,temp13_dag2,temp14_dag2,temp15_dag2,temp16_dag2,temp17_dag2,temp18_dag2,temp19_dag2,temp20_dag2,temp1_dag3,temp2_dag3,temp3_dag3,temp4_dag3,temp5_dag3,temp6_dag3,temp7_dag3,temp8_dag3,temp9_dag3,temp10_dag3,temp11_dag3,temp12_dag3,temp13_dag3,temp14_dag3,temp15_dag3,temp16_dag3,temp17_dag3,temp18_dag3,temp19_dag3,temp20_dag3,temp1_dag4,temp2_dag4,temp3_dag4,temp4_dag4,temp5_dag4,temp6_dag4,temp7_dag4,temp8_dag4,temp9_dag4,temp10_dag4,temp11_dag4,temp12_dag4,temp13_dag4,temp14_dag4,temp15_dag4,temp16_dag4,temp17_dag4,temp18_dag4,temp19_dag4,temp20_dag4,temp1_dag5,temp2_dag5,temp3_dag5,temp4_dag5,temp5_dag5,temp6_dag5,temp7_dag5,temp8_dag5,temp9_dag5,temp10_dag5,temp11_dag5,temp12_dag5,temp13_dag5,temp14_dag5,temp15_dag5,temp16_dag5,temp17_dag5,temp18_dag5,temp19_dag5,temp20_dag5,temp1_dag6,temp2_dag6,temp3_dag6,temp4_dag6,temp5_dag6,temp6_dag6,temp7_dag6,temp8_dag6,temp9_dag6,temp10_dag6,temp11_dag6,temp12_dag6,temp13_dag6,temp14_dag6,temp15_dag6,temp16_dag6,temp17_dag6,temp18_dag6,temp19_dag6,temp20_dag6,temp1_dag7,temp2_dag7,temp3_dag7,temp4_dag7,temp5_dag7,temp6_dag7,temp7_dag7,temp8_dag7,temp9_dag7,temp10_dag7,temp11_dag7,temp12_dag7,temp13_dag7,temp14_dag7,temp15_dag7,temp16_dag7,temp17_dag7,temp18_dag7,temp19_dag7,temp20_dag7,temp1_dag8,temp2_dag8,temp3_dag8,temp4_dag8,temp5_dag8,temp6_dag8,temp7_dag8,temp8_dag8,temp9_dag8,temp10_dag8,temp11_dag8,temp12_dag8,temp13_dag8,temp14_dag8,temp15_dag8,temp16_dag8,temp17_dag8,temp18_dag8,temp19_dag8,temp20_dag8,temp1_dag9,temp2_dag9,temp3_dag9,temp4_dag9,temp5_dag9,temp6_dag9,temp7_dag9,temp8_dag9,temp9_dag9,temp10_dag9,temp11_dag9,temp12_dag9,temp13_dag9,temp14_dag9,temp15_dag9,temp16_dag9,temp17_dag9,temp18_dag9,temp19_dag9,temp20_dag9,temp1_dag10,temp2_dag10,temp3_dag10,temp4_dag10,temp5_dag10,temp6_dag10,temp7_dag10,temp8_dag10,temp9_dag10,temp10_dag10,temp11_dag10,temp12_dag10,temp13_dag10,temp14_dag10,temp15_dag10,temp16_dag10,temp17_dag10,temp18_dag10,temp19_dag10,temp20_dag10,temp1_dag11,temp2_dag11,temp3_dag11,temp4_dag11,temp5_dag11,temp6_dag11,temp7_dag11,temp8_dag11,temp9_dag11,temp10_dag11,temp11_dag11,temp12_dag11,temp13_dag11,temp14_dag11,temp15_dag11,temp16_dag11,temp17_dag11,temp18_dag11,temp19_dag11,temp20_dag11,temp1_dag12,temp2_dag12,temp3_dag12,temp4_dag12,temp5_dag12,temp6_dag12,temp7_dag12,temp8_dag12,temp9_dag12,temp10_dag12,temp11_dag12,temp12_dag12,temp13_dag12,temp14_dag12,temp15_dag12,temp16_dag12,temp17_dag12,temp18_dag12,temp19_dag12,temp20_dag12,temp1_dag13,temp2_dag13,temp3_dag13,temp4_dag13,temp5_dag13,temp6_dag13,temp7_dag13,temp8_dag13,temp9_dag13,temp10_dag13,temp11_dag13,temp12_dag13,temp13_dag13,temp14_dag13,temp15_dag13,temp16_dag13,temp17_dag13,temp18_dag13,temp19_dag13,temp20_dag13,temp1_dag14,temp2_dag14,temp3_dag14,temp4_dag14,temp5_dag14,temp6_dag14,temp7_dag14,temp8_dag14,temp9_dag14,temp10_dag14,temp11_dag14,temp12_dag14,temp13_dag14,temp14_dag14,temp15_dag14,temp16_dag14,temp17_dag14,temp18_dag14,temp19_dag14,temp20_dag14 FROM OES_ST_V4_VITALS_temp_man_20"))
```

```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_WO_Complicaties tot en jan 2021_selected'")$COLUMN_NAME), collapse = ",")
#columns_string



oes_wo_complicaties <- as.data.frame(dbGetQuery(con, "SELECT [Case number],Datum_operatie_nieuw,Pneumonie,[Datum pneumonie],[POD pneumonie],Naadlekkage,[Datum naadlekkage],[POD naadlekkage],[Ongecompliceerd infectieus],F10,F11,F12,F13,Datum_operatie_nieuw1,F15,[Opaname IC],[Opname duur],[Heropname IC],[Heropname zkh <30 dagen] FROM [OES_WO_Complicaties tot en jan 2021_selected]"))
```

```{r}
#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_MED_TXT'")$COLUMN_NAME), collapse = ",")
#columns_string
med_txt <- as.data.frame(dbGetQuery(con, "SELECT mode,Case_number,Datum_operatie_nieuw,Pt_nummer,dag0,dag1,dag2,dag3,dag4,dag5,dag6,dag7,dag8,dag9,dag10,dag11,dag12,dag13,dag14 FROM OES_ST_V4_MED_TXT"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_MED_TXT_2'")$COLUMN_NAME), collapse = ",")
#columns_string
#med_txt_2 <- as.data.frame(dbGetQuery(con, "SELECT patientnr,OK_DAT,[POD NAADLEKKAGE],[OK+DAT_NAAD],Verslag_dag_1,Verslag_dag_2,Verslag_dag_3,Verslag_dag_4,Verslag_dag_5,Verslag_dag_6,Verslag_dag_7,Verslag_dag_8,Verslag_dag_9,Verslag_dag_10,Verslag_dag_11,Verslag_dag_12,Verslag_dag_13,Verslag_dag_14 FROM OES_ST_V4_MED_TXT_2"))

#columns_string <- paste(cbind(dbGetQuery(con, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'OES_ST_V4_VERPL_TXT'")$COLUMN_NAME), collapse = ",")
#columns_string
verpl_txt <- as.data.frame(dbGetQuery(con, "SELECT mode,Case_number,Datum_operatie_nieuw,Pt_nummer,dag0,dag1,dag2,dag3,dag4,dag5,dag6,dag7,dag8,dag9,dag10,dag11,dag12,dag13,dag14 FROM OES_ST_V4_VERPL_TXT"))
```

```{r}

```

```{r}

```

```{r}

```

```{r}
tibble(
    column = colnames(overview),
    missing = overview %>% map_dbl(~is.na(.) %>% mean())
) %>% 
    arrange(-missing) #%>%
    #filter(missing > .05)
sapply(overview, function(x) sum(is.na(x))) #missing values per column
```

